### ISSUE TITLE
How to add in embeds?

### ISSUE THREAD

**Issue by BlackKnight683** [AKORA-Studios/DiscordWelcomeCard#5]
Will this one work?
```js
    //Generating the actual welcome Card
    const image = await welcomeImage(message.member, {
      theme: 'circuit',
      text: {
        title: 'Welcome',
        text: user.tag,
        subtitle: 'please read the Rules',
        color: imgText
      },
      avatar: {
        image: user.displayAvatarURL({ format: 'png' }),
        outlineWidth: 2,
        outlineColor: imgText
      },
      background: imgBG,
      blur: 1,
      border: true,
      rounded: true
    });
    embed.setImage("attachments://welcome.png")

**Comment by A-K-O-R-A** [comment]
Nope, this won't work, which version of discord.js are u using?

**Comment by BlackKnight683** [comment]
i got it working, it was to add it as an image and send in the files (v13) btw

One more question... it shows this on usage, how do i add those fonts?
![image](https://user-images.githubusercontent.com/75422863/133506454-ed4597e4-a667-443a-89c8-78a4f3339b9a.png)

**Comment by BlackKnight683** [comment]
Sorry for late reply its kinda 3am for me 😅

**Comment by A-K-O-R-A** [comment]
What Operating System are u on?

**Comment by BlackKnight683** [comment]
Linux

**Comment by A-K-O-R-A** [comment]
So this is a Windows default Font as far as I know, u can download it(or copy it from a Windows machine) and use the `registerFont` method by Canvas to fix the error.

**Comment by BlackKnight683** [comment]
oh alright, Tysm!
