### ISSUE TITLE
Sorry if this isn't a bug but a question

### ISSUE THREAD

**Issue by Badgaming01** [AKORA-Studios/DiscordWelcomeCard#6]
Where will I put the welcome card script really confused about it

**Comment by DragonCat4012** [comment]
uhm this depends complety on your bots structure ^^" but there is a example usage in the [README.md](https://github.com/AKORA-Studios/DiscordWelcomeCard/blob/main/README.md) file

**Comment by Badgaming01** [comment]
No I mean like what file I will put it like index,js or config

**Comment by Badgaming01** [comment]
> uhm this depends complety on your bots structure ^^" but there is a example usage in the [README.md](https://github.com/AKORA-Studios/DiscordWelcomeCard/blob/main/README.md) file

I mean like where I will put the script index.js or what

**Comment by DragonCat4012** [comment]
Yeah index.js file ^^"
